# chart-repo: argo/argo
# chart-version: latest
# chart-ingress: true

ui:
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
      - INGRESS_DOMAIN
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

useDefaultArtifactRepo: true
useStaticCredentials: false

artifactRepository:
  s3:
    bucket: ARTIFACT_REPOSITORY
    endpoint: s3.amazonaws.com
