# chart-repo: stable/gocd
# chart-version: latest
# chart-ingress: true
# chart-pvc: gocd-server ReadWriteOnce 2Gi

server:
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
      - INGRESS_DOMAIN
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    storageSize: 2Gi
    #:EFS:storageClass: "efs"
    existingClaim: gocd-server
